### ISSUE TITLE
Issues with Rx from Ti?

### ISSUE THREAD

**Issue by ikt32** [DSchndr/serial2ti83#2]
So this is an old repo, but I'll try my luck anyway. My hope was actually to contact @fingalo about this, but their fork doesn't have an Issues tab.

I've been trying to communicate with my Ti-83+ using this sketch. jw0k's variant works, but failed to transfer larger files so I tried my luck with these forks. I just can't get them to work, however. I've tried it on the Arduino Uno and Nano, checked the cables, but things just don't seem to work. It looks like the calculator doesn't send anything back, as the TX light stays off.

With *this* fork, the TX light does light up when manually sending from the calculator, though the calculator doesn't seem to respond to the bytes sent from the PC.

With the fork from @fingalo - the last additional checks in getByte - always times out.

I looked through things, but I'm kinda out of ideas. How do you debug such a thing?

**Comment by fingalo** [comment]
Hello itk,
have you changed the connection to use A0 and A1  when using this and fingalo code for uno board?

Also I've create an issues tab.
Regards 
fingalo

**Comment by ikt32** [comment]
Thanks, I'll continue this discussion in an issue in your fork then :)
